# Generated by Django 5.1.6 on 2025-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
